# Generated by Django 5.1.1 on 2024-12-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Start_date', models.DateField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
