# Generated by Django 5.1.1 on 2024-12-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Photo',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
