# Generated by Django 5.1.1 on 2024-12-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
