# Generated by Django 5.1.1 on 2024-12-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
