# Generated by Django 5.1.1 on 2024-12-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_employee_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='First_name',
            new_name='Name',
        ),
    ]
